/*
 * Datos de configuración del generador.
 * Cada plataforma define cómo se estructura y se entrega el prompt;
 * cada tipo de proyecto y stack aporta requisitos específicos de SEO y GSAP.
 */
window.PG_DATA = {
  platforms: [
    {
      id: 'aistudio',
      name: 'Google AI Studio',
      badge: 'Gemini',
      icon: '✦',
      format: 'xml',
      split: true,
      agent: false,
      hint: 'Pega las «Instrucciones del sistema» en el campo System instructions y el prompt en el chat. En modo Build, Gemini genera una app completa lista para previsualizar.',
      role: 'Eres un ingeniero front-end sénior y diseñador UI/UX con experiencia en SEO técnico y animación web con GSAP. Trabajas dentro de Google AI Studio.',
      delivery: [
        'Entrega todos los archivos completos, sin fragmentos ni comentarios del tipo «resto del código aquí».',
        'Antepón a cada bloque de código la ruta del archivo (p. ej. `src/components/Hero.tsx`).',
        'Si trabajas en modo Build, asegúrate de que la vista previa funcione sin pasos manuales.',
      ],
      tips: 'Temperatura recomendada: 0.4–0.7 para código. Activa «Grounding with Google Search» solo si necesitas datos actuales. Las etiquetas XML ayudan a Gemini a separar contexto, tarea y restricciones.',
    },
    {
      id: 'cloudstudio',
      name: 'Google Cloud Studio',
      badge: 'Vertex AI · Firebase',
      icon: '☁',
      format: 'xml',
      split: true,
      agent: false,
      hint: 'Pensado para Vertex AI Studio / Firebase Studio: incluye despliegue en Google Cloud (Cloud Run o Firebase Hosting), variables de entorno y buenas prácticas de producción.',
      role: 'Eres un arquitecto de soluciones web en Google Cloud y desarrollador front-end sénior, experto en SEO técnico, rendimiento y animación con GSAP.',
      delivery: [
        'Entrega el código completo por archivo, con su ruta, listo para desplegar.',
        'Incluye la configuración de despliegue (Dockerfile para Cloud Run o `firebase.json` para Firebase Hosting) y los comandos `gcloud`/`firebase` necesarios.',
        'Gestiona secretos con Secret Manager o variables de entorno; nunca los escribas en el código.',
        'Configura caché de estáticos y compresión (Cloud CDN o cabeceras de Firebase Hosting).',
      ],
      tips: 'En Vertex AI Studio guarda el prompt como plantilla para reutilizarlo. En Firebase Studio, pega el prompt en el agente del workspace y revisa los cambios antes de desplegar.',
    },
    {
      id: 'chatgpt',
      name: 'ChatGPT',
      badge: 'OpenAI',
      icon: '◎',
      format: 'md',
      split: false,
      agent: false,
      hint: 'Prompt único en Markdown. Para proyectos largos, pide que use Canvas y avanza por fases para no cortar la respuesta.',
      role: 'Actúa como un desarrollador front-end sénior, diseñador UI/UX y especialista en SEO técnico con amplia experiencia en animación web con GSAP.',
      delivery: [
        'Trabaja por fases: primero la estructura de archivos y la arquitectura, después el código archivo por archivo.',
        'Entrega cada archivo en un bloque de código independiente precedido de su ruta.',
        'Si la respuesta se va a cortar, detente en un archivo completo y espera a que escriba «continúa».',
      ],
      tips: 'Usa Canvas para iterar sobre el código. Si repites este tipo de proyecto, guarda las reglas como instrucciones personalizadas o en un GPT propio.',
    },
    {
      id: 'antigravity',
      name: 'Antigravity',
      badge: 'Agente IDE',
      icon: '⟁',
      format: 'md',
      split: false,
      agent: true,
      rulesName: 'Reglas del workspace',
      rulesFile: 'reglas-proyecto.md',
      hint: 'Prompt de tarea para el agente en modo Planning + reglas del workspace. El agente planifica, implementa y verifica en el navegador integrado.',
      role: 'Eres un agente de desarrollo autónomo trabajando en Google Antigravity. Actúas como ingeniero front-end sénior, diseñador UI/UX y especialista en SEO técnico y animación con GSAP.',
      delivery: [
        'Antes de escribir código, genera un plan de implementación (artefacto) y una lista de tareas; espera mi aprobación si hay decisiones de arquitectura abiertas.',
        'Implementa por tareas pequeñas y verificables.',
        'Arranca el servidor de desarrollo y verifica cada sección en el navegador integrado: capturas en escritorio (1440 px) y móvil (390 px).',
        'Al terminar, entrega un walkthrough con lo realizado, capturas y cómo ejecutar el proyecto.',
      ],
      tips: 'Usa el modo Planning para proyectos nuevos y Fast para ajustes. Guarda el bloque de reglas en las reglas del workspace (Customizations › Rules) para que se apliquen en todas las conversaciones.',
    },
    {
      id: 'codex',
      name: 'Codex',
      badge: 'OpenAI agente',
      icon: '⌘',
      format: 'md',
      split: false,
      agent: true,
      rulesName: 'AGENTS.md',
      rulesFile: 'AGENTS.md',
      hint: 'Tarea para Codex (nube, CLI o IDE) + archivo AGENTS.md en la raíz del repositorio con convenciones y comandos de verificación.',
      role: 'Eres Codex, un agente de ingeniería de software. Actúas como desarrollador front-end sénior con experiencia en SEO técnico y animación con GSAP.',
      delivery: [
        'Lee AGENTS.md antes de empezar y respeta sus convenciones.',
        'Haz cambios pequeños y atómicos con mensajes de commit descriptivos (Conventional Commits).',
        'Ejecuta lint, comprobación de tipos, build y tests antes de dar la tarea por terminada; corrige cualquier fallo.',
        'Termina con un resumen tipo pull request: cambios, decisiones, cómo probarlo y pendientes.',
      ],
      tips: 'Coloca AGENTS.md en la raíz del repo. En Codex en la nube, lanza varias tareas en paralelo (p. ej. SEO y animaciones) sobre ramas separadas.',
    },
  ],

  // Plataformas de diseño de interfaces (modo «Diseño UI»).
  designPlatforms: [
    {
      id: 'stitch',
      name: 'Google Stitch',
      badge: 'Google Labs · Gemini',
      icon: '✂',
      mode: 'stitch',
      hint: 'Stitch rinde mejor con un prompt inicial claro y luego un cambio o pantalla por mensaje. Se generan un prompt inicial y los prompts de cada pantalla para pegarlos uno a uno.',
      role: 'Actúa como diseñador/a UI/UX sénior.',
      delivery: [
        'Mantén el mismo tema, tipografía, radios y componentes en todas las pantallas.',
        'Usa textos reales, no lorem ipsum.',
      ],
      tips: 'Pega primero el prompt inicial y después cada prompt de pantalla por separado. Para ajustes, pide un solo cambio por mensaje (p. ej. «haz el botón principal más grande»). Puedes adjuntar un boceto o captura como referencia y exportar el resultado a Figma o a HTML/CSS.',
    },
    {
      id: 'claudedesign',
      name: 'Claude Design',
      badge: 'Anthropic',
      icon: '◈',
      mode: 'brief',
      hint: 'Brief completo en Markdown para Claude Design: diseños y prototipos a partir de la conversación, con sistema de diseño reutilizable y entrega a desarrollo.',
      role: 'Actúa como director/a de arte y diseñador/a de producto sénior, con dominio de sistemas de diseño, accesibilidad y diseño para SEO.',
      delivery: [
        'Empieza por el sistema de diseño (tokens y componentes base) y después compón las pantallas con él.',
        'Presenta las variantes una junto a otra con una breve justificación de cada una.',
        'Cuando te pida cambios, aplícalos de forma coherente en todas las pantallas afectadas.',
        'Prepara el diseño para la entrega a desarrollo (por ejemplo, a Claude Code): nombres claros de componentes y tokens.',
      ],
      tips: 'Si tu equipo ya tiene un sistema de diseño, adjúntalo o enlázalo al empezar para que Claude lo aplique. Itera con comentarios concretos sobre cada pantalla y, al terminar, pasa el diseño a Claude Code para implementarlo.',
    },
    {
      id: 'figmamake',
      name: 'Figma Make',
      badge: 'Figma',
      icon: '◐',
      mode: 'brief',
      hint: 'Prompt para Figma Make: genera prototipos funcionales dentro de Figma. Adjunta frames o tu librería de componentes para que respete tu estilo.',
      role: 'Actúa como diseñador/a de producto sénior y prototipador/a en Figma.',
      delivery: [
        'Genera un prototipo navegable entre las pantallas indicadas.',
        'Usa Auto Layout, variables de color y tipografía, y componentes con variantes para los estados.',
        'Nombra capas y componentes de forma clara y en el idioma del proyecto.',
      ],
      tips: 'Adjunta un frame de referencia o selecciona tu librería antes de enviar el prompt. Pide los cambios por pantalla o componente para no rehacer todo el prototipo.',
    },
    {
      id: 'v0',
      name: 'v0',
      badge: 'Vercel',
      icon: '▲',
      mode: 'brief',
      hint: 'Prompt para v0: genera la interfaz directamente como componentes React con Tailwind CSS y shadcn/ui, lista para publicar en Vercel.',
      role: 'Actúa como diseñador/a UI y desarrollador/a front-end experto/a en React, Tailwind CSS y shadcn/ui.',
      delivery: [
        'Construye la interfaz con componentes de shadcn/ui y Tailwind CSS, con tokens de tema en variables CSS.',
        'Separa cada pantalla y cada componente reutilizable en su propio archivo.',
        'Usa imágenes provisionales con proporciones reales y texto alternativo descriptivo.',
      ],
      tips: 'Empieza por la pantalla principal y añade las demás en mensajes sucesivos. Cuando el diseño te convenza, publícalo en Vercel o descárgalo e implementa las animaciones GSAP con el modo Desarrollo web.',
    },
  ],

  devices: {
    'web-responsive': 'una web responsive (escritorio 1440 px y móvil 390 px)',
    'web-desktop': 'una web de escritorio (1440 px)',
    'mobile-app': 'una app móvil (390 × 844 px, iOS y Android)',
    tablet: 'una interfaz para tablet (1024 × 768 px)',
  },

  fidelity: {
    wireframe: 'wireframes en escala de grises centrados en estructura y jerarquía',
    hifi: 'mockups de alta fidelidad con el estilo visual final',
    prototype: 'un prototipo interactivo de alta fidelidad con navegación entre pantallas',
  },

  dsBases: {
    custom: 'sistema de diseño propio a partir de la marca',
    material: 'Material Design 3 adaptado a la marca',
    hig: 'Apple Human Interface Guidelines adaptadas a la marca',
    shadcn: 'shadcn/ui + Tailwind CSS con tema personalizado',
  },

  uiStates: {
    interaction: 'hover, foco visible y pulsado',
    empty: 'estados vacíos',
    loading: 'carga y skeletons',
    error: 'errores y validación de formularios',
  },

  stacks: [
    {
      id: 'html',
      name: 'HTML + CSS + JavaScript (sin framework)',
      seo: 'HTML estático semántico: todo el contenido indexable debe estar en el HTML servido, no inyectado con JavaScript.',
      gsap: 'Carga GSAP desde CDN (`https://cdn.jsdelivr.net/npm/gsap@3.13/dist/gsap.min.js` y los plugins necesarios) con `defer`, y registra los plugins con `gsap.registerPlugin()`.',
      commands: 'Servidor local: `npx serve .` · Validación: HTML validator + Lighthouse',
      structure: '`index.html`, `css/styles.css`, `js/main.js`, `js/animations.js`, `assets/`',
    },
    {
      id: 'astro',
      name: 'Astro (SSG) + TypeScript',
      seo: 'Genera HTML estático por página (SSG). Usa un componente `<SEO />` en el layout y `@astrojs/sitemap`.',
      gsap: 'Instala `gsap` por npm e inicializa las animaciones en `<script>` de componentes. Si usas View Transitions, reinicializa en `astro:page-load` y limpia en `astro:before-swap`.',
      commands: '`npm run dev` · `npm run build` · `npx astro check`',
      structure: '`src/layouts/`, `src/components/`, `src/pages/`, `src/scripts/animations.ts`, `public/`',
    },
    {
      id: 'next',
      name: 'Next.js (App Router) + TypeScript + Tailwind CSS',
      seo: 'Usa la Metadata API (`metadata` / `generateMetadata`), `app/sitemap.ts`, `app/robots.ts` y Server Components para que el contenido llegue renderizado.',
      gsap: 'Instala `gsap` y `@gsap/react`. Anima solo en Client Components (`"use client"`) con el hook `useGSAP()` y un `scope` para limpiar automáticamente.',
      commands: '`npm run dev` · `npm run build` · `npm run lint` · `npx tsc --noEmit`',
      structure: '`app/`, `components/`, `components/animations/`, `lib/`, `public/`',
    },
    {
      id: 'react',
      name: 'React + Vite + TypeScript',
      seo: 'Es una SPA: añade prerenderizado/SSG de las rutas públicas y gestiona `<head>` por ruta (p. ej. `react-helmet-async`). Advierte si alguna página queda sin HTML indexable.',
      gsap: 'Instala `gsap` y `@gsap/react`; usa `useGSAP()` con `scope` y refs, nunca selectores globales.',
      commands: '`npm run dev` · `npm run build` · `npm run lint`',
      structure: '`src/components/`, `src/pages/`, `src/hooks/`, `src/animations/`, `public/`',
    },
    {
      id: 'nuxt',
      name: 'Nuxt 3 (Vue) + TypeScript',
      seo: 'Usa `useSeoMeta()` / `useHead()`, renderizado SSR o `nuxt generate`, y el módulo `@nuxtjs/sitemap`.',
      gsap: 'Crea las animaciones en `onMounted` dentro de `gsap.context()` y llama a `ctx.revert()` en `onUnmounted`. Registra GSAP en un plugin de cliente (`plugins/gsap.client.ts`).',
      commands: '`npm run dev` · `npm run build` · `npm run generate`',
      structure: '`pages/`, `components/`, `composables/useGsap.ts`, `plugins/`, `public/`',
    },
    {
      id: 'sveltekit',
      name: 'SvelteKit + TypeScript',
      seo: 'Activa `prerender` en las rutas públicas y gestiona metadatos con `<svelte:head>`.',
      gsap: 'Inicializa en `onMount` con `gsap.context()` y devuelve la función de limpieza (`ctx.revert()`); también puedes usar acciones de Svelte (`use:`).',
      commands: '`npm run dev` · `npm run build` · `npm run check`',
      structure: '`src/routes/`, `src/lib/components/`, `src/lib/animations/`, `static/`',
    },
  ],

  projectTypes: [
    {
      id: 'landing',
      name: 'Landing page de conversión',
      sections: 'Hero con propuesta de valor, Beneficios, Cómo funciona, Testimonios, Precios, FAQ, CTA final, Footer',
      schema: ['Organization', 'WebPage', 'FAQPage'],
      goals: 'Maximizar la conversión: una sola llamada a la acción repetida, jerarquía visual clara y prueba social.',
      seo: 'Una sola palabra clave principal por página; H1 con la propuesta de valor; FAQ con marcado FAQPage para ganar espacio en resultados.',
      gsap: 'Entrada escalonada del hero, contadores animados en cifras, revelado de secciones con ScrollTrigger y micro-interacciones en el CTA.',
      features: ['Formulario de captación con validación accesible', 'Seguimiento de eventos de conversión (sin bloquear el render)'],
    },
    {
      id: 'corporate',
      name: 'Web corporativa',
      sections: 'Inicio, Sobre nosotros, Servicios, Casos de éxito, Equipo, Blog, Contacto',
      schema: ['Organization', 'WebSite', 'BreadcrumbList', 'Service'],
      goals: 'Transmitir confianza y autoridad, explicar servicios y generar contactos cualificados.',
      seo: 'Arquitectura de información por servicios (una URL por servicio), enlazado interno, breadcrumbs y página de contacto con NAP consistente.',
      gsap: 'Animaciones sobrias: fundidos y desplazamientos cortos al hacer scroll, líneas de tiempo en la historia de la empresa.',
      features: ['Menú accesible con submenús', 'Formulario de contacto con protección anti-spam'],
    },
    {
      id: 'portfolio',
      name: 'Portfolio / estudio creativo',
      sections: 'Hero, Proyectos destacados, Detalle de proyecto, Sobre mí/nosotros, Servicios, Contacto',
      schema: ['Person', 'CreativeWork', 'ImageObject', 'BreadcrumbList'],
      goals: 'Mostrar el trabajo con impacto visual y diferenciarse, sin sacrificar velocidad ni accesibilidad.',
      seo: 'Cada proyecto en su propia URL indexable con texto descriptivo; imágenes con `alt` descriptivo, nombres de archivo significativos y formatos AVIF/WebP.',
      gsap: 'Transiciones entre páginas, galería con Flip, títulos con SplitText, cursor personalizado y scroll horizontal fijado con ScrollTrigger.',
      features: ['Filtro de proyectos por categoría', 'Lightbox accesible'],
    },
    {
      id: 'ecommerce',
      name: 'Tienda online (e-commerce)',
      sections: 'Inicio, Listado de categoría con filtros, Ficha de producto, Carrito, Checkout, Cuenta, Políticas',
      schema: ['Product', 'Offer', 'AggregateRating', 'BreadcrumbList', 'Organization'],
      goals: 'Facilitar la búsqueda y compra, reducir el abandono de carrito y transmitir confianza.',
      seo: 'Fichas de producto con descripciones únicas, `canonical` en variantes y filtros, paginación rastreable, marcado Product con precio y disponibilidad.',
      gsap: 'Micro-interacciones al añadir al carrito (Flip hacia el icono del carrito), galería de producto fluida y animaciones muy ligeras que no afecten al INP.',
      features: ['Carrito persistente', 'Filtros accesibles sin recargar la página', 'Estados de carga y vacíos'],
    },
    {
      id: 'blog',
      name: 'Blog / revista digital',
      sections: 'Portada, Listado por categorías, Artículo, Autor, Búsqueda, Newsletter',
      schema: ['Article', 'BlogPosting', 'Person', 'BreadcrumbList', 'WebSite'],
      goals: 'Facilitar la lectura y el descubrimiento de contenido, y aumentar suscriptores.',
      seo: 'Marcado Article/BlogPosting con autor y fechas, tabla de contenidos con anclas, RSS, E-E-A-T (página de autor) y enlazado interno entre artículos relacionados.',
      gsap: 'Barra de progreso de lectura, revelado suave de imágenes y animaciones mínimas en el cuerpo del texto para no distraer.',
      features: ['Tabla de contenidos automática', 'Tiempo de lectura', 'Artículos relacionados'],
    },
    {
      id: 'saas',
      name: 'SaaS / aplicación web',
      sections: 'Home de producto, Funcionalidades, Integraciones, Precios, Documentación, Changelog, Login/Registro',
      schema: ['SoftwareApplication', 'Organization', 'FAQPage', 'Offer'],
      goals: 'Explicar el producto con claridad, convertir a pruebas gratuitas y reducir fricción en el registro.',
      seo: 'Páginas públicas renderizadas en servidor; el área privada con `noindex`. Páginas por caso de uso y comparativas para captar búsquedas de intención alta.',
      gsap: 'Demostraciones del producto animadas con timelines, secciones fijadas (pin) con ScrollTrigger que muestran funcionalidades paso a paso.',
      features: ['Tabla de precios con conmutador mensual/anual', 'Modo oscuro', 'Estados de error accesibles'],
    },
    {
      id: 'school',
      name: 'Escuela / academia',
      sections: 'Inicio, Cursos, Ficha de curso, Profesorado, Galería de alumnos, Calendario, Matrícula, Contacto',
      schema: ['EducationalOrganization', 'Course', 'Event', 'Person', 'LocalBusiness'],
      goals: 'Captar matrículas y solicitudes de información mostrando la calidad de la enseñanza y los trabajos del alumnado.',
      seo: 'Una URL por curso con marcado Course (proveedor, modalidad, duración), SEO local para búsquedas «curso de … en [ciudad]» y ficha de Google Business Profile coherente.',
      gsap: 'Galería de trabajos con revelado al scroll, títulos con SplitText y transiciones suaves entre cursos.',
      features: ['Buscador/filtro de cursos por disciplina y nivel', 'Formulario de matrícula o reserva de clase de prueba'],
    },
    {
      id: 'restaurant',
      name: 'Restaurante / hostelería',
      sections: 'Inicio, Carta, Reservas, Galería, Sobre nosotros, Ubicación y horario, Contacto',
      schema: ['Restaurant', 'Menu', 'LocalBusiness', 'OpeningHoursSpecification'],
      goals: 'Aumentar reservas y visitas, mostrar la carta de forma apetecible y facilitar cómo llegar.',
      seo: 'SEO local: NAP idéntico al de Google Business Profile, carta en HTML (nunca solo en PDF o imagen), horarios con marcado estructurado.',
      gsap: 'Imágenes de platos con parallax suave, revelado de la carta por categorías y transiciones cálidas.',
      features: ['Botón de reserva siempre visible en móvil', 'Mapa con carga diferida'],
    },
    {
      id: 'event',
      name: 'Evento / congreso',
      sections: 'Hero con fecha y cuenta atrás, Ponentes, Agenda, Entradas, Sede, Patrocinadores, FAQ',
      schema: ['Event', 'Place', 'Offer', 'Person', 'FAQPage'],
      goals: 'Vender entradas y comunicar agenda, ponentes y logística.',
      seo: 'Marcado Event con fechas, lugar, estado y ofertas para aparecer en resultados de eventos; páginas de ponentes indexables.',
      gsap: 'Cuenta atrás animada, agenda con pestañas animadas y logotipos de patrocinadores en marquesina infinita.',
      features: ['Agenda filtrable por día y track', 'Añadir al calendario (.ics)'],
    },
    {
      id: 'local',
      name: 'Negocio local / servicios',
      sections: 'Inicio, Servicios, Zonas de trabajo, Opiniones, Presupuesto, Contacto',
      schema: ['LocalBusiness', 'Service', 'AggregateRating', 'FAQPage'],
      goals: 'Generar llamadas y solicitudes de presupuesto desde búsquedas locales.',
      seo: 'Páginas de servicio + ciudad sin contenido duplicado, NAP coherente, reseñas, mapa y enlaces «click-to-call».',
      gsap: 'Animaciones discretas; prioridad absoluta a la velocidad en móvil.',
      features: ['Botón de llamada y WhatsApp fijo en móvil', 'Formulario de presupuesto por pasos'],
    },
  ],

  gsapPlugins: [
    { id: 'ScrollTrigger', label: 'ScrollTrigger', desc: 'animaciones ligadas al scroll, pin y scrub', level: 'subtle' },
    { id: 'SplitText', label: 'SplitText', desc: 'revelado de títulos por líneas, palabras o caracteres (con `aria` accesible)', level: 'moderate' },
    { id: 'Flip', label: 'Flip', desc: 'transiciones de layout (filtros, galerías, cambios de estado)', level: 'moderate' },
    { id: 'ScrollSmoother', label: 'ScrollSmoother', desc: 'scroll suavizado y efectos parallax con `data-speed`', level: 'immersive' },
    { id: 'Observer', label: 'Observer', desc: 'gestos de rueda, táctiles y puntero unificados', level: 'immersive' },
    { id: 'MotionPathPlugin', label: 'MotionPath', desc: 'elementos que siguen trazados SVG', level: 'immersive' },
    { id: 'DrawSVGPlugin', label: 'DrawSVG', desc: 'dibujo progresivo de trazos SVG', level: 'moderate' },
    { id: 'MorphSVGPlugin', label: 'MorphSVG', desc: 'transformación entre formas SVG', level: 'immersive' },
    { id: 'Draggable', label: 'Draggable + Inertia', desc: 'carruseles y elementos arrastrables con inercia', level: 'immersive' },
    { id: 'CustomEase', label: 'CustomEase', desc: 'curvas de easing propias de la marca', level: 'moderate' },
  ],

  gsapLevels: {
    none: 'Sin animaciones GSAP.',
    subtle: 'Sutil: fundidos y desplazamientos cortos (≤ 24 px, 0.4–0.7 s), solo para guiar la atención.',
    moderate: 'Moderada: coreografía de entrada del hero, revelados al scroll escalonados, micro-interacciones y algún efecto destacado por página.',
    immersive: 'Inmersiva: narrativa guiada por el scroll (storytelling), secciones fijadas, parallax, transiciones entre páginas y efectos tipográficos; el sitio debe sentirse de nivel Awwwards sin perder rendimiento.',
  },
};
